### ISSUE TITLE
Need suggestion to create info file for population setting

### ISSUE THREAD

**Issue by sushanta26** [AleksandarStan/Laspinema#1]
Hi 
Thank you so much for amazing script for Fst analysis.

I need your help to create info.file in your script you used is as "laspinema_info.txt", could you please provide sample fasta alignment and metadata file you used for Fst analysis so that I could get a idea about data structure of input file.

once again thank you so much for your effort and script.

Regards 
Sushanta

**Comment by AleksandarStan** [comment]
Hi Sushanta,

All the files used can be found at the figshare link provided in the article (https://doi.org/10.6084/m9.figshare.20116118). The fasta alignment used is named "Consensus alignment vcf". Beware that for popgen analyses I excluded one strain (D2d).
The info file should look like this:

ind	pop
D2a	D2
D2b	D2
D2c	D2
D3a	D3
D3b	D3
D3c	D3
D3d	D3

Below you can find the laspinema info text file.
Thanks for your comment, it is appreciated.

/Aleks
[laspinema_info.txt](https://github.com/AleksandarStan/Laspinema/files/12254644/laspinema_info.txt)

**Comment by sushanta26** [comment]
Hi 
Thank you so much for assistance. unfortunately I am facing problem with "laspinema_nd_sw_50 <- data.frame(windows, laspinema_nuc_div_sw_50, row.names = NULL) Error: object 'laspinema_nuc_div_sw_50' not found" this section of code , I think variable is not declared in R script, could you please shed light on this portion, 
Appreciate your help.

Thank you

**Comment by AleksandarStan** [comment]
Hi

I've just updated the script. There was one line missing with defining the variable (line 19 in the code).
I tested the script now and should work.

/Aleks
